CONFIG_ZMK_KSCAN_MATRIX_POLLING=y
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BEFORE_INPUTS=20
CONFIG_ZMK_KSCAN_MATRIX_WAIT_BETWEEN_OUTPUTS=20
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
